name: Server CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: pnpm install --frozen-lockfile
        working-directory: unfollow-ninja-server
        run: pnpm install
      - name: lint
        working-directory: unfollow-ninja-server
        run: pnpm lint
      - name: build
        working-directory: unfollow-ninja-server
        run: pnpm build
      - name: test
        working-directory: unfollow-ninja-server
        run: pnpm specs
      - name: Archive test results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: unfollow-ninja-server/test-results

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create an empty env file
        working-directory: unfollow-ninja-server
        run: touch .env
      - name: build
        working-directory: unfollow-ninja-server/tests
        run: docker-compose build
      - name: run tests
        working-directory: unfollow-ninja-server/tests
        run: docker-compose up --exit-code-from tests
